version: '3.4'

services:
    catalogdb:
        container_name: catalogdb
        restart: always
        ports:
            - "27017:27017"
    basketdb:
        container_name: basketdb
        restart: always
        ports:
            - "6379:6379"
    orderdb:
        container_name: orderdb
        restart: always
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"
    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            # rabbitmq
            - "5672:5672"
            # management console
            - "15672:15672"

    catalog.api:
        container_name: catalogapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CatalogDBSettings:ConnectionString=mongodb://catalogdb:27017"
        depends_on:
            - catalogdb
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8000:80"
    basket.api:
        container_name: basketapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:Redis=basketdb:6379"
            - "EventBus:HostName=rabbitmq"
        depends_on:
            - basketdb
            - rabbitmq
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8001:80"
    ordering.api:
        container_name: orderingapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:MSSqlServer=server=orderdb;database=orderdb;user id=sa;password=yourStrong(!)Password;"
            - "EventBus:HostName=rabbitmq"
        depends_on:
            - orderdb
            - rabbitmq
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8002:80"